// Códigos de error estandarizados
const ERROR_CODES = {
  // Autenticación (AUTH_xxx)
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_USER_NOT_FOUND: 'AUTH_002',
  AUTH_INVALID_PASSWORD: 'AUTH_003',
  AUTH_EMAIL_EXISTS: 'AUTH_004',
  AUTH_TOKEN_INVALID: 'AUTH_005',
  AUTH_TOKEN_EXPIRED: 'AUTH_006',
  AUTH_UNAUTHORIZED: 'AUTH_007',
  AUTH_FORBIDDEN: 'AUTH_008',
  
  // Pedidos (ORDER_xxx)
  ORDER_NOT_FOUND: 'ORDER_001',
  ORDER_INVALID_SERVICE: 'ORDER_002',
  ORDER_INVALID_PRICE_MODEL: 'ORDER_003',
  ORDER_INVALID_STATE_TRANSITION: 'ORDER_004',
  ORDER_ALREADY_PAID: 'ORDER_005',
  ORDER_CANNOT_PAY: 'ORDER_006',
  ORDER_UNAUTHORIZED_ACCESS: 'ORDER_007',
  ORDER_CANNOT_DELETE: 'ORDER_008',
  
  // Servicios (SERVICE_xxx)
  SERVICE_NOT_FOUND: 'SERVICE_001',
  SERVICE_INACTIVE: 'SERVICE_002',
  SERVICE_INVALID_MODEL: 'SERVICE_003',
  
  // Usuarios (USER_xxx)
  USER_NOT_FOUND: 'USER_001',
  USER_INACTIVE: 'USER_002',
  USER_EMAIL_EXISTS: 'USER_003',
  USER_CANNOT_DEACTIVATE_SELF: 'USER_004',
  USER_CANNOT_DEMOTE_LAST_ADMIN: 'USER_005',
  USER_HAS_ACTIVE_ORDERS: 'USER_006',
  USER_ALREADY_ACTIVE: 'USER_007',
  USER_ALREADY_INACTIVE: 'USER_008',
  
  // Validación (VALIDATION_xxx)
  VALIDATION_ERROR: 'VALIDATION_001',
  VALIDATION_MISSING_FIELD: 'VALIDATION_002',
  
  // Sistema (SYSTEM_xxx)
  SYSTEM_DATABASE_ERROR: 'SYSTEM_001',
  SYSTEM_UNKNOWN_ERROR: 'SYSTEM_002'
};

module.exports = ERROR_CODES;